Iter9
Axel791/metricsalert pull request #5
Opened 2024-12-26 17:56 UTC by Axel791

2024-12-27 20:30 UTC, s-shpak requested changes

2024-12-27 20:30 UTC, s-shpak commented on internal/server/handlers/deprecated/get_metric.go
> +		http.Error(w, "invalid metric", http.StatusInternalServerError)
Кажется, что здесь неправильное сообщение об ошибке

2024-12-27 20:30 UTC, s-shpak commented on internal/server/handlers/get_metric.go
> +		http.Error(w, "failed to encode response", http.StatusInternalServerError)
Пользователю не стоит отдавать никакую информацию про ввнутренние ошибки сервиса -- это небезопасно. Используй https://pkg.go.dev/net/http#StatusText

2024-12-27 20:30 UTC, s-shpak commented on internal/server/services/file_service.go
> +func NewFileStorageService(
В этом спринте мы добавляем обособленную часть функционала к хранилищу: запись в файл. То есть новый тип хранилища полностью повторяет функционал MemoryStore и расширяет его. Но мы оставляем возможность запустить сервис без записи в файл. Потому кажется логичным не изменять существующую структуру, и не дуплицировать функционал, а написать обертку над MemoryStore.

Для этого можно использовать композицию и встроить MemoryStore в новую структуру FileStore. При вызове сохранения, например, новая структура будет вызывать вначале добавление новой записи в память (через встроенный объект), а потом сохранение в файл.

В этом случае убедись, что ты выполняешь инициализацию нужного типа при старте сервиса (можно использовать паттерн Factory, как разбирали на первом вебинаре).

2024-12-27 20:30 UTC, s-shpak commented on internal/shared/logger/log.go
> +func InitLogger() {
Я не советую использовать глобальный логгер. Такая практика встречается, но я предлагаю не использовать ее в курсе.

Единственный аргумент для использования глобального логгера -- возможность не передавать его напрямую в компоненты, где он используется. При этом использование глобального логгера несет в себе все минусы глобальных переменных, а также минусы самого глобального логгера.

Можно выделить две основные проблемы "глобального" подхода: 

1. Теперь ты не можешь кастомизировать логгер для конкретного компонента, в котором он используется. Например, если логгер явным образом передается в компонент при его инициализации, то ты можешь настроить его так, чтобы к каждому сообщению добавлялось поле с именем компонента, который это сообщение сгенерировал. Вобщем, локальные логгеры кастомизируются легко, глобальные -- сложно.

2. С одной стороны, удобно, что логгер не надо явным образом передавать в компонент. С другой, теперь мы создаем неявные зависимости: поведение компонента зависит от логгера (если, например, логгер не будет корректно проинициализирован, то компонент тоже поломается, т.к. при вызове логгера будет падать). Неявные зависимости хуже чем явные. Потому с моей т.з. передавать логгер явным образом как аргумент функции, или как поле объекта -- лучше, чем спрятать его в глобальную переменную

2025-01-06 09:10 UTC, s-shpak requested changes
Выдай мне, пожалуйста, права контрибьютора, чтобы я мог резовлить комментарии

2025-01-06 09:10 UTC, s-shpak commented on cmd/agent/main.go
> +			atomic.AddInt64(&pollCount, 1)
Правильность такого подхода зависит от того, с какой точностью ты хочешь собирать данные с агентов. Мне кажется, что метрики должны приходить с высокой точностью, потому нельзя допускать ситуации, когда произойдет сбор метрик на строке 37, потом их отправка на строке 76, а потом изменение счетчика. В данной реализации это возможно

2025-01-06 09:10 UTC, s-shpak commented on internal/agent/sender/client.go
> +		if err != nil {
Нужно ли продолжать попытки отправки сообщений, если мы получили эту ошибку ?

2025-01-06 16:39 UTC, Axel791 commented on internal/agent/sender/client.go
> +		if err != nil {
Думаю, что стоит оставить, т.к. мы можем увидеть с какой попытки все таки подключается к серверу(если подключение произошло). Пользователю более понятно сколько подключений было, логи это сильно не засоряет, а если даже сильно много логов, то мы не сможем пропустить, что у нас были попытки подключения. Даже если ориентироваться на другие программы, например, когда Celery пытается установить соединение с Redis, то мы тоже можем наблюдать сообщение с попытками.

2025-01-06 16:46 UTC, Axel791 commented on internal/server/services/file_service.go
> +func NewFileStorageService(
Не совсем понял, правильно ли сделал? Я добавил доп хранилище, которое над MemoryStore. И не совсем видимо я понял задумку с Factory, на вебинаре, к сожалению, не был. Если сделал не так что-то, то не совсем данной реализации понимаю, что именно

2025-01-07 11:14 UTC, s-shpak commented on cmd/agent/main.go
> +				PollCount:     pollCount,
Тебе надо чуть лучше разобраться с моделью синхронизации в Go (https://go.dev/ref/mem#synchronization). Здесь ты не защищаешь PollCount корректно: если это атомарная величина, то копировать ее также надо атомарно.

Другое дело, что перенесением инкремента PollCount ты не решил проблему: теперь счетчик может увеличиться дважды, а сбор метрик произойдет только один раз до отправки.

Используй просто мьютекс, и не отправляй данные до их полного сбора. Это будет работать медленее, но корректно во всех случаях.

2025-01-07 11:14 UTC, s-shpak commented on internal/server/repositories/file_metrics.go
> +	mutex       sync.Mutex
Правильно хранить указатель на мьютекс, а не сам мьютекс -- мьютекс нельзя копировать после инициализации. Почему это так мы, возмжно, разберем во второй части курса, пока это правило лучше просто запомнить

2025-01-07 11:14 UTC, s-shpak commented on internal/server/services/file_service.go
> +func NewFileStorageService(
Не совсем. Это не очень важно, но если хочешь, то возьми 1-1, чтобы обсудить это подробнее

2025-01-07 11:15 UTC, s-shpak requested changes
См. комментарии

2025-01-11 21:21 UTC, s-shpak approved these changes

2025-01-12 19:07 UTC, merged